name: Nest.js Server Production Deploy

on:
  release:
    types: [published]

jobs:
  build-and-deploy:
    if: startsWith(github.event.release.tag_name, 'server-')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4.2.2
      
      - name: Setup pnpm
        uses: pnpm/action-setup@v4.1.0
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"

      - name: Install Dependencies
        run: |
          pnpm install

      - name: Create .env file
        run: |
          echo "TEST=${{ secrets.TEST }}" >> .env

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract tag without prefix
        id: extract_tag
        run: |
          RAW_TAG=${{ github.event.release.tag_name }}
          CLEAN_TAG=${RAW_TAG#app-}
          echo "clean_tag=${CLEAN_TAG}" >> $GITHUB_ENV

      - name: Log clean tag
        run: |
          echo ${{ env.clean_tag }}
          echo "${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPOSITORY_SERVER }}:${{ env.clean_tag }}"

      - name: Build and push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/server.prod.Dockerfile
          platforms: linux/amd64/v3
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPOSITORY_SERVER }}:${{ env.clean_tag }}
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPOSITORY_SERVER }}:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST_SERVER }}
          username: ${{ secrets.EC2_USERNAME_SERVER }}
          key: ${{ secrets.EC2_SSH_KEY_SERVER }}
          script: |
            cd ${{ secrets.PROJECT_PATH_SERVER }}
            sudo docker compose pull
            sudo docker compose down
            sudo docker compose up -d
            sudo docker image prune -f
